from professor_scraper.Settings.auth import(
    BASE_DIR,
    SECRET_KEY,
    DEBUG,
    ALLOWED_HOSTS,
    INSTALLED_APPS,
    ROOT_URLCONF,
    WSGI_APPLICATION,
    AUTH_PASSWORD_VALIDATORS,
    REST_FRAMEWORK,
    SIMPLE_JWT,
    LANGUAGE_CODE ,
    TIME_ZONE,
    USE_I18N,
    USE_TZ,
)

from professor_scraper.Settings.database import DATABASES 
from professor_scraper.Settings.middleware import MIDDLEWARE
from professor_scraper.Settings.static import (
    STATIC_URL,
    STATICFILES_DIRS,
    STATIC_ROOT,
    MEDIA_URL,
    MEDIA_URL_2,
    MEDIA_ROOT
)


from professor_scraper.Settings.templates import TEMPLATES


ALLOWED_HOSTS,
AUTH_PASSWORD_VALIDATORS,
BASE_DIR,
DATABASES,
DEBUG,
INSTALLED_APPS,
LANGUAGE_CODE,
MEDIA_ROOT,
MEDIA_URL,
MEDIA_URL_2,
MIDDLEWARE,
REST_FRAMEWORK,
ROOT_URLCONF,
SECRET_KEY,
SIMPLE_JWT,
STATICFILES_DIRS,
STATIC_ROOT,
STATIC_URL,
TEMPLATES,
TIME_ZONE,
USE_I18N,
USE_TZ,
WSGI_APPLICATION